---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xrepositories.ecr.aws.qaware.de
spec:
  compositeTypeRef:
    apiVersion: ecr.aws.qaware.de/v1beta1
    kind: XRepository
  resources:
    - name: repository
      base:
        apiVersion: ecr.aws.upbound.io/v1beta1
        kind: Repository
        spec:
          deletionPolicy: Delete
          forProvider:
            forceDelete: true
            encryptionConfiguration:
              - encryptionType: AES256
            imageScanningConfiguration:
              - scanOnPush: true
            imageTagMutability: IMMUTABLE
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.repositoryName"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"