apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: aws-ecr
  annotations:
    provider: aws
    service: ecr
spec:
  crossplane:
    version: ">=v1.2.0-0"
  dependsOn:
    - provider: crossplane/provider-aws
      version: ">=v0.23.0-0"
