apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: xrd-repository-configuration
spec:
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-ecr
      version: ">=v0.47.0-0"
  crossplane:
    version: ">=v1.14.0-0"