apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  # StorageBucket names must be globally unique
  name: k8s-native-iac-lab-demo
  namespace: config-connector
  annotations:
    # delete the bucket when the resource is deleted or not (abandon)
    cnrm.cloud.google.com/deletion-policy: "none"
    # delete all files in the bucket when the bucket is deleted
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    stage: demo
spec:
  location: EU
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 7
  versioning:
    enabled: true
  uniformBucketLevelAccess: true
