---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.s3.aws.qaware.de
spec:
  compositeTypeRef:
    apiVersion: s3.aws.qaware.de/v1beta1
    kind: XBucket
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete          
          forProvider:
            region: eu-central-1          
            objectLockEnabled: false
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.bucketName"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.labels"
          toFieldPath: "metadata.labels"
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.annotations"
          toFieldPath: "metadata.annotations"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
    - name: encryption
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketServerSideEncryptionConfiguration
        spec:
          forProvider:
            region: eu-central-1
            rule:
              - applyServerSideEncryptionByDefault:
                  - sseAlgorithm: AES256
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.bucketName"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-sse"
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.labels"
          toFieldPath: "spec.forProvider.bucketSelector.matchLabels"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
    - name: lifecycle
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketLifecycleConfiguration
        spec:
          forProvider:
            region: eu-central-1
            rule:
              - id: 90-days-rule
                expiration:
                  - days: 90
                status: Enabled
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.bucketName"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-lifecycle"
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.labels"
          toFieldPath: "spec.forProvider.bucketSelector.matchLabels"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
