apiVersion: s3.aws.qaware.de/v1beta1
kind: Bucket
metadata:
  name: example-xrd-bucket
  annotations:
    crossplane.io/external-name: example-xrd-bucket-eu-central-1
  labels:
    app.kubernetes.io/name: example-xrd
spec:
  parameters:
    bucketName: example-xrd-bucket
    region: eu-central-1