apiVersion: s3.aws.qaware.de/v1beta1
kind: Bucket
metadata:
  namespace: default
  name: cnn-mainz-bucket-eu-central-1
  annotations:
    crossplane.io/external-name: cnn-mainz-bucket-eu-central-1
spec:
  parameters:
    bucketName: cnn-mainz-bucket-eu-central-1
    region: eu-central-1