apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane-system
  namespace: flux-system
spec:
  chart:
    spec:
      chart: crossplane
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
      version: "1.10.1"
  interval: 1h0m0s
  releaseName: crossplane-system
  targetNamespace: crossplane-system