apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: ack-demo-bucket-cnn2022
  annotations:
    services.k8s.aws/region: eu-central-1
spec:
  name: ack-demo-bucket-cnn2022
  encryption:
    rules:
    - applyServerSideEncryptionByDefault:
        sseAlgorithm: AES256
  tagging:
    tagSet:
    - key: Meetup
      value: Cloud-native Night Mainz