apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: ack-demo-bucket
  annotations:
    services.k8s.aws/region: eu-north-1
spec:
  name: ack-demo-bucket
  encryption:
    rules:
    - applyServerSideEncryptionByDefault:
        sseAlgorithm: AES256
  tagging:
    tagSet:
    - key: Meetup
      value: Platform Engineering Meetup