apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  # name must be unique across all of your buckets in AWS, append a hash to the name
  generateName: example-bucket-
  labels:
    app.kubernetes.io/name: example
spec:
  # determine wether to Delete or Orphan the resource on deletion
  deletionPolicy: Delete
  forProvider:
    region: eu-central-1
    objectLockEnabled: false
    tags:
      Name: ExampleBucket
  providerConfigRef:
    name: default