apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketACL
metadata:
  name: example-bucket-acl
spec:
  forProvider:
    region: eu-central-1
    acl: private
    bucketSelector:
      matchLabels:
        app.kubernetes.io/name: example