apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: k8s-nginx
  namespace: pulumi-system
spec:
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  stack: lreimer/k8s-nginx/dev
  projectRepo: https://github.com/pulumi/examples
  repoDir: kubernetes-ts-nginx/
  branch: "refs/heads/master"
  destroyOnFinalize: true