---
apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: example-aurora-serverless
  labels:
    app.kubernetes.io/name: example
spec:
  deletionPolicy: Delete
  forProvider:
    applyImmediately: true
    region: eu-central-1
    availabilityZones:
      - eu-central-1a
      - eu-central-1b
      - eu-central-1c
    vpcSecurityGroupIDs:
      - sg-0a4c5663
    backupRetentionPeriod: 5
    databaseName: test
    engine: aurora-postgresql
    engineMode: serverless
    engineVersion: "10.14"
    storageEncrypted: true
    skipFinalSnapshot: true
    enableHTTPEndpoint: true
    masterUsername: lreimer
    masterUserPasswordSecretRef:
      key: password
      name: test-aurora-admin
      namespace: crossplane-system
  writeConnectionSecretToRef:
    name: test-aurora-serverless
    namespace: default
  providerConfigRef:
    name: default