apiVersion: ecr.aws.upbound.io/v1beta1
kind: Repository
metadata:
  name: example-repository
  labels:
    app.kubernetes.io/name: example
spec:
  deletionPolicy: Delete
  forProvider:
    forceDelete: true
    region: eu-central-1
    encryptionConfiguration:
      - encryptionType: AES256
    imageScanningConfiguration:
      - scanOnPush: true
    imageTagMutability: IMMUTABLE
  providerConfigRef:
    name: default