apiVersion: ecr.aws.crossplane.io/v1beta1
kind: Repository
metadata:
  name: mastering-gitops
  labels:
    region: eu-central-1
spec:
  deletionPolicy: Delete
  forProvider:
    forceDelete: true
    region: eu-central-1
    imageScanningConfiguration:
      scanOnPush: true
    imageTagMutability: IMMUTABLE
  providerConfigRef:
    name: providerconfig-aws