apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: pulumi-operator-crds
  namespace: pulumi-system
spec:
  interval: 5m0s
  path: ./deploy/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: pulumi-operator
  validation: client
  targetNamespace: pulumi-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: pulumi-operator-yaml
  namespace: pulumi-system
spec:
  interval: 5m0s
  path: ./deploy/yaml
  prune: true
  dependsOn:
    - name: pulumi-operator-crds
  sourceRef:
    kind: GitRepository
    name: pulumi-operator
  validation: client
  targetNamespace: pulumi-system
