apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositorylifecycles.ecr.aws.cloud.qaware.de
spec:
  group: ecr.aws.cloud.qaware.de
  names:
    kind: RepositoryLifecycle
    listKind: RepositoryLifecycleList
    plural: repositorylifecycles
    singular: repositorylifecycle
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: RepositoryLifecycle is the Schema for the repositorylifecycles
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RepositoryLifecycleSpec defines the desired state of RepositoryLifecycle
            properties:
              lifecyclePolicyText:
                description: The LifecyclePolicyText JSON text. This member is required.
                type: string
              repositoryName:
                description: The name of the repository to receive the policy.
                type: string
            required:
            - lifecyclePolicyText
            - repositoryName
            type: object
          status:
            description: RepositoryLifecycleStatus defines the observed state of RepositoryLifecycle
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
